# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the Linux wirless network device drivers.
#

obj-$(CONFIG_BCMDHD) += bcmdhd/
obj-$(CONFIG_RTL8723CS) += rtl8188fu/
obj-$(CONFIG_RTL8723CS) += rtl8723cs/
obj-$(CONFIG_RTL8723CS) += rtl8723du/
obj-$(CONFIG_RTL8723CS) += rtl8822bs/
obj-$(CONFIG_RTL8723CS) += rtl8822cu/
obj-$(CONFIG_XR819_WLAN) += xr819/
obj-$(CONFIG_XR829_WLAN) += xr829/
obj-$(CONFIG_SPARD_WLAN_SUPPORT) += uwe5622/
obj-$(CONFIG_AIC_WLAN_SUPPORT) += aic8800/
obj-$(CONFIG_ATBM_WIRELESS) += atbm6023is/
