# SPDX-License-Identifier: GPL-2.0

# Minimal System
obj-y += clk/
obj-y += pinctrl/
obj-y += uart/
obj-y += timer/

# Basic System
obj-y += dma/
obj-y += rtc/
# obj-y += bus/
obj-y += dumpreg/
obj-y += watchdog/
obj-y += i2c/
obj-y += spi/
obj-y += ledc/
obj-y += pwm/
# obj-y += ir-tx/
# obj-y += ir-rx/
obj-y += gpadc/
obj-y += lradc/
# obj-y += rtp/
obj-y += usb/
obj-y += iommu/
obj-y += gmac/

# Power Management
obj-y += irqchip/
obj-y += standby/
obj-y += thermal/
obj-y += nvmem/
# obj-y += pm_domain/
obj-y += power/
obj-y += cpufreq/

# Input
obj-y += input/

# Storage
obj-y += mmc/

# Graphics
obj-y += video/
obj-y += g2d/
obj-y += vin/

# Multi-Media
obj-y += ve/

# Sound
# obj-y += sound/

# Security
obj-y += smc/
obj-y += sid/
# obj-y += secure_storage/

# Net
obj-y += net/

# Wireless
obj-y += bluetooth/

# Misc
obj-y += misc/

# Drm
obj-y += drm/

# Open source GPU
obj-y += gpu/panfrost/

